name: snap_state
description: "A production-ready, ultra-lightweight state management ecosystem for Flutter. Combines signals reactivity, controller lifecycles, and dependency injection to eliminate boilerplate."
version: 1.0.4
homepage: "https://github.com/rupkumar-dev/snap-state"

environment:
  sdk: ^3.12.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
assets:
  - description: The flutter snap logo.
    path: assets/logo.png
